// Auto-generated by data_vector.py
#ifndef DATA_H_
#define DATA_H_

#define N 8

static const float src[N] = {
  -1.46254302f, 1.38973495f, 1.05509848f, -0.97972390f, -0.01825965f, -0.20203574f, 0.60637189f, 1.15489340f
};

static const float golden[N] = {
  0.01619959f, 0.28069360f, 0.20086383f, 0.02625364f, 0.06866702f, 0.05713935f, 0.12823963f, 0.22194334f
};

#endif // DATA_H_
